# Generated by Django 4.2.1 on 2023-05-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGestionInventario', '0002_remove_material_matunidadmedida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleentradamaterial',
            name='devEstado',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo')], db_comment='estado del Elemento', max_length=7),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='eleEstado',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo')], db_comment='Estado del elemento devolutivo', max_length=10),
        ),
    ]
